package org.example.day9;

import java.util.LinkedList;

import static org.example.day9.Directions.RIGHT;
import static org.example.day9.Directions.LEFT;
import static org.example.day9.Directions.DOWN;
import static org.example.day9.Directions.UP;


public class Day9 {

    private final LinkedList<Position> positions;
    private Position tail;

    public Day9() {
        positions = new LinkedList<>();
        traverse();
    }

    public int getNumberOfVisitedPositions() {
        return Position.getNumberOfVisited();
    }

    private void traverse() {
        int x = 0;
        int y = 0;

        tail = new Position(0, 0);

        positions.addFirst(tail);
        Position.addToVisited(tail);

        for (String line : INPUT.lines().toList()) {
            String[] lines = line.split(" ");
            String direction = lines[0].trim();
            int number = Integer.parseInt(lines[1].trim());

            for (int i = 0; i < number; i++) {
                if (direction.equals(RIGHT.label)) {
                    x++;
                }
                if (direction.equals(LEFT.label)) {
                    x--;
                }
                if (direction.equals(UP.label)) {
                    y++;
                }
                if (direction.equals(DOWN.label)) {
                    y--;
                }
                positions.push(new Position(x, y));
                adjustTail(direction);
            }
        }
    }

    private void adjustTail(String direction) {
        boolean remove = false;
        Position head = positions.peek();

        if (head != null) {
            int newX = getXPosition(head, tail, direction);
            int newY = getYPosition(head, tail, direction);

            if (tail.getX() < head.getX() - 1) {
                newX++;
                remove = true;
            }
            if (tail.getX() > head.getX() + 1) {
                newX--;
                remove = true;
            }
            if (tail.getY() < head.getY() - 1) {
                newY++;
                remove = true;
            }
            if (tail.getY() > head.getY() + 1) {
                newY--;
                remove = true;
            }
            if (remove) {
                positions.removeLast();
                tail = positions.getLast();
                tail.setX(newX);
                tail.setY(newY);
            }
            Position.addToVisited(tail);
        }
    }

    private int getXPosition(Position head, Position tail, String direction) {
        if ((head.getY() - tail.getY() == 2 || head.getY() - tail.getY() == -2)
                && (direction.equals(UP.label) || direction.equals(DOWN.label))) {
            return head.getX();
        }
        return tail.getX();
    }

    private int getYPosition(Position head, Position tail, String direction) {
        if ((head.getX() - tail.getX() == 2 || head.getX() - tail.getX() == -2)
            && (direction.equals(LEFT.label) || direction.equals(RIGHT.label))) {
            return head.getY();
        }
        return tail.getY();
    }

    private static final String INPUT =
            """
                   D 1
                   U 2
                   R 2
                   U 1
                   R 1
                   U 2
                   L 2
                   D 1
                   L 2
                   R 1
                   L 1
                   R 1
                   U 2
                   D 2
                   L 2
                   R 2
                   L 2
                   R 1
                   L 1
                   D 1
                   U 1
                   R 1
                   U 2
                   D 1
                   U 1
                   D 1
                   R 2
                   D 1
                   U 1
                   R 1
                   L 2
                   R 2
                   U 2
                   R 2
                   L 2
                   R 2
                   U 2
                   D 2
                   R 1
                   U 2
                   D 2
                   U 2
                   D 1
                   L 1
                   D 1
                   L 1
                   R 2
                   D 2
                   R 2
                   D 1
                   R 2
                   L 1
                   R 1
                   L 2
                   D 2
                   U 1
                   D 1
                   R 2
                   L 2
                   D 2
                   L 2
                   D 2
                   L 1
                   R 2
                   L 1
                   D 1
                   L 2
                   D 1
                   U 1
                   R 1
                   U 1
                   R 2
                   D 2
                   R 1
                   U 2
                   D 1
                   L 2
                   D 2
                   L 1
                   D 1
                   L 1
                   D 1
                   R 1
                   L 1
                   U 1
                   D 2
                   U 1
                   D 2
                   R 1
                   D 2
                   L 2
                   U 1
                   L 1
                   R 1
                   D 1
                   U 1
                   D 1
                   R 1
                   U 2
                   L 1
                   D 1
                   U 2
                   R 2
                   D 2
                   R 1
                   D 1
                   R 1
                   L 1
                   R 2
                   U 1
                   D 1
                   L 1
                   U 3
                   L 2
                   U 2
                   L 2
                   D 2
                   L 1
                   R 3
                   D 1
                   U 1
                   L 3
                   D 3
                   U 1
                   L 2
                   U 1
                   R 2
                   U 3
                   D 2
                   L 3
                   U 2
                   R 2
                   D 2
                   U 1
                   R 1
                   L 3
                   D 2
                   L 3
                   D 1
                   U 3
                   R 3
                   U 3
                   D 3
                   U 3
                   L 3
                   U 1
                   D 1
                   U 1
                   D 3
                   R 3
                   D 3
                   U 3
                   R 3
                   L 3
                   R 2
                   U 3
                   D 3
                   L 1
                   R 2
                   D 2
                   U 1
                   R 1
                   L 2
                   D 3
                   R 3
                   D 1
                   U 1
                   D 1
                   U 2
                   D 1
                   R 1
                   D 2
                   R 2
                   L 1
                   D 2
                   L 1
                   R 2
                   L 3
                   R 3
                   L 1
                   U 3
                   R 3
                   U 3
                   D 1
                   L 3
                   R 1
                   L 1
                   R 2
                   L 1
                   U 2
                   R 1
                   D 2
                   R 3
                   L 3
                   R 2
                   U 3
                   R 3
                   L 1
                   R 1
                   L 1
                   U 1
                   L 2
                   R 2
                   L 3
                   D 2
                   L 2
                   R 3
                   D 3
                   U 1
                   L 2
                   D 3
                   U 3
                   D 3
                   R 1
                   U 1
                   L 2
                   U 1
                   L 1
                   R 1
                   U 3
                   L 2
                   R 1
                   D 4
                   R 3
                   D 3
                   L 3
                   D 4
                   R 4
                   L 3
                   R 2
                   D 2
                   R 4
                   U 2
                   D 3
                   L 1
                   R 2
                   U 4
                   R 3
                   D 2
                   U 1
                   D 4
                   R 1
                   D 3
                   U 3
                   L 2
                   R 2
                   L 3
                   R 3
                   L 4
                   D 3
                   L 2
                   U 3
                   L 1
                   R 2
                   D 4
                   R 3
                   U 3
                   L 2
                   U 3
                   D 2
                   L 4
                   D 4
                   L 4
                   U 4
                   R 1
                   D 1
                   R 3
                   U 3
                   R 3
                   D 3
                   L 1
                   U 1
                   R 3
                   L 2
                   R 2
                   D 2
                   R 4
                   U 4
                   L 4
                   D 3
                   L 2
                   R 4
                   L 2
                   D 1
                   L 2
                   R 4
                   U 2
                   L 2
                   U 3
                   L 4
                   R 2
                   L 4
                   D 2
                   L 1
                   D 4
                   L 3
                   U 2
                   D 1
                   R 4
                   U 2
                   D 1
                   R 4
                   D 4
                   U 3
                   R 3
                   U 4
                   L 1
                   D 3
                   U 1
                   D 3
                   R 2
                   U 1
                   R 3
                   L 4
                   R 1
                   L 4
                   D 3
                   R 4
                   U 2
                   L 1
                   D 4
                   L 2
                   R 4
                   L 2
                   R 3
                   L 3
                   U 2
                   R 3
                   L 2
                   R 1
                   D 4
                   L 3
                   D 3
                   L 5
                   D 1
                   R 3
                   D 4
                   L 4
                   R 2
                   D 5
                   R 2
                   L 2
                   D 5
                   U 2
                   D 1
                   U 2
                   D 3
                   L 2
                   D 1
                   L 3
                   U 1
                   D 3
                   R 2
                   U 4
                   R 5
                   D 5
                   U 3
                   R 1
                   D 5
                   U 1
                   D 4
                   R 1
                   U 4
                   D 4
                   R 4
                   U 5
                   D 4
                   R 1
                   L 1
                   D 5
                   L 1
                   D 4
                   U 1
                   D 2
                   U 1
                   D 1
                   R 1
                   D 2
                   R 2
                   D 1
                   L 5
                   R 3
                   L 4
                   D 3
                   R 5
                   D 4
                   U 2
                   R 2
                   U 2
                   D 2
                   U 5
                   L 4
                   D 5
                   L 5
                   R 3
                   D 2
                   U 4
                   D 2
                   L 3
                   R 2
                   L 1
                   U 2
                   R 4
                   L 5
                   R 4
                   D 1
                   U 5
                   D 4
                   L 5
                   R 2
                   U 4
                   D 3
                   L 3
                   D 3
                   L 1
                   U 5
                   L 4
                   R 1
                   U 5
                   D 4
                   R 2
                   L 1
                   D 2
                   R 3
                   L 2
                   R 5
                   D 5
                   R 2
                   L 1
                   U 3
                   D 2
                   L 1
                   U 1
                   R 4
                   U 1
                   D 1
                   U 1
                   R 2
                   U 3
                   R 4
                   L 4
                   R 1
                   U 3
                   R 3
                   D 1
                   L 3
                   R 4
                   L 1
                   U 5
                   D 6
                   U 2
                   L 4
                   D 2
                   U 1
                   D 4
                   R 5
                   L 2
                   R 6
                   L 6
                   U 1
                   D 4
                   L 3
                   D 5
                   U 4
                   L 4
                   R 2
                   D 2
                   L 3
                   D 1
                   U 6
                   L 6
                   R 2
                   D 2
                   U 3
                   L 6
                   R 1
                   U 5
                   R 5
                   U 5
                   D 1
                   L 2
                   U 1
                   R 1
                   D 5
                   L 6
                   R 1
                   D 4
                   R 3
                   L 3
                   D 2
                   U 5
                   D 6
                   U 3
                   D 6
                   U 4
                   L 2
                   R 1
                   U 5
                   D 2
                   L 1
                   D 4
                   U 1
                   R 2
                   L 2
                   R 4
                   D 1
                   L 6
                   D 5
                   L 6
                   R 6
                   L 3
                   U 5
                   R 4
                   D 4
                   L 3
                   D 2
                   L 1
                   R 4
                   U 3
                   R 2
                   U 2
                   R 5
                   D 1
                   U 5
                   D 4
                   R 4
                   L 5
                   D 5
                   U 3
                   R 1
                   U 4
                   L 5
                   U 1
                   D 2
                   U 4
                   D 4
                   L 1
                   U 2
                   L 3
                   U 5
                   R 1
                   L 5
                   U 1
                   R 4
                   D 2
                   L 6
                   U 6
                   R 6
                   U 5
                   R 6
                   U 6
                   L 5
                   U 1
                   L 5
                   D 3
                   R 1
                   D 4
                   L 3
                   D 7
                   U 1
                   D 4
                   R 2
                   U 4
                   D 4
                   U 7
                   D 3
                   L 3
                   D 3
                   R 4
                   D 7
                   R 4
                   D 5
                   U 3
                   L 5
                   R 5
                   D 5
                   L 2
                   R 3
                   L 2
                   R 4
                   U 2
                   L 4
                   U 7
                   L 2
                   U 6
                   D 3
                   U 6
                   R 2
                   D 2
                   U 6
                   L 2
                   R 4
                   U 5
                   D 2
                   R 4
                   L 2
                   D 2
                   R 1
                   D 3
                   R 1
                   D 3
                   U 4
                   D 2
                   L 4
                   D 1
                   L 5
                   U 1
                   R 2
                   D 3
                   U 4
                   D 4
                   L 5
                   R 2
                   D 2
                   U 1
                   D 7
                   L 7
                   R 2
                   L 6
                   D 4
                   R 7
                   L 3
                   U 2
                   D 2
                   U 4
                   L 5
                   D 4
                   U 4
                   R 5
                   L 5
                   D 2
                   R 5
                   L 7
                   U 1
                   D 7
                   L 3
                   R 4
                   L 5
                   D 5
                   L 2
                   R 5
                   L 3
                   R 2
                   L 4
                   R 1
                   D 3
                   L 5
                   R 2
                   D 4
                   U 3
                   R 3
                   L 5
                   D 3
                   R 1
                   D 5
                   R 5
                   L 1
                   D 6
                   R 5
                   D 4
                   U 2
                   L 4
                   U 1
                   D 3
                   L 2
                   D 7
                   R 4
                   L 1
                   U 6
                   R 8
                   L 2
                   U 2
                   R 1
                   U 7
                   D 6
                   L 7
                   R 3
                   U 5
                   R 4
                   L 8
                   D 2
                   R 4
                   U 8
                   L 6
                   R 1
                   L 7
                   D 5
                   L 3
                   R 6
                   U 1
                   D 7
                   L 2
                   U 7
                   R 1
                   U 6
                   L 3
                   R 8
                   D 5
                   L 4
                   R 4
                   L 6
                   D 6
                   R 3
                   L 2
                   U 5
                   R 3
                   D 1
                   R 7
                   L 1
                   U 8
                   D 2
                   U 3
                   D 1
                   L 2
                   U 6
                   L 1
                   U 4
                   R 6
                   U 7
                   R 1
                   D 1
                   U 8
                   R 1
                   D 7
                   L 1
                   U 4
                   D 1
                   U 2
                   R 8
                   U 1
                   D 6
                   R 1
                   U 1
                   R 5
                   L 7
                   R 3
                   D 3
                   U 8
                   L 6
                   D 7
                   U 8
                   L 4
                   R 1
                   L 7
                   U 4
                   D 3
                   L 3
                   R 6
                   D 3
                   U 8
                   L 5
                   D 8
                   L 1
                   U 7
                   R 6
                   L 5
                   U 8
                   R 2
                   L 8
                   R 7
                   L 8
                   U 7
                   D 7
                   U 3
                   D 4
                   U 8
                   D 5
                   U 3
                   L 4
                   D 4
                   U 8
                   R 7
                   U 7
                   L 7
                   R 4
                   L 1
                   D 8
                   R 9
                   D 4
                   R 8
                   L 5
                   R 9
                   U 5
                   D 1
                   L 5
                   D 7
                   U 3
                   R 5
                   U 1
                   R 3
                   U 2
                   D 9
                   U 5
                   R 3
                   U 4
                   R 3
                   D 4
                   U 7
                   D 9
                   L 7
                   D 3
                   U 1
                   R 3
                   U 4
                   L 3
                   R 8
                   L 3
                   U 8
                   R 6
                   L 6
                   D 7
                   L 7
                   D 4
                   L 3
                   U 5
                   L 2
                   R 5
                   D 3
                   U 6
                   L 9
                   R 9
                   D 9
                   U 9
                   R 4
                   D 8
                   R 8
                   D 5
                   L 7
                   U 2
                   R 4
                   L 8
                   R 4
                   L 2
                   R 3
                   L 7
                   R 1
                   U 1
                   L 5
                   D 5
                   R 9
                   D 8
                   U 7
                   L 3
                   R 5
                   D 1
                   U 1
                   R 5
                   D 6
                   U 9
                   D 8
                   R 4
                   D 7
                   L 1
                   U 5
                   D 8
                   L 4
                   D 4
                   L 7
                   D 8
                   R 5
                   U 9
                   D 2
                   L 1
                   R 2
                   U 8
                   D 4
                   L 6
                   D 1
                   L 5
                   D 6
                   R 9
                   U 1
                   L 9
                   U 4
                   D 6
                   R 8
                   L 5
                   R 1
                   L 2
                   R 7
                   D 8
                   L 4
                   R 3
                   U 2
                   L 7
                   U 2
                   D 1
                   R 8
                   U 8
                   L 1
                   R 1
                   D 2
                   U 3
                   L 5
                   D 6
                   L 3
                   U 6
                   R 2
                   L 5
                   U 6
                   L 5
                   D 3
                   L 6
                   D 2
                   L 4
                   U 10
                   R 4
                   D 7
                   U 4
                   D 4
                   L 5
                   U 3
                   L 9
                   R 7
                   D 1
                   L 4
                   U 4
                   D 5
                   R 5
                   D 4
                   U 1
                   D 3
                   R 1
                   L 6
                   U 1
                   D 1
                   L 4
                   U 5
                   D 10
                   R 4
                   U 5
                   R 1
                   U 2
                   R 4
                   D 6
                   L 7
                   U 1
                   R 2
                   D 1
                   L 7
                   D 4
                   U 9
                   L 6
                   D 8
                   R 3
                   U 7
                   R 8
                   U 2
                   D 5
                   R 3
                   U 10
                   D 3
                   R 3
                   U 1
                   R 8
                   D 10
                   R 3
                   D 1
                   U 10
                   L 5
                   U 8
                   D 6
                   L 9
                   D 5
                   U 1
                   R 9
                   U 3
                   D 3
                   R 8
                   L 9
                   D 8
                   U 3
                   R 2
                   D 3
                   L 7
                   D 3
                   R 10
                   L 9
                   U 2
                   R 8
                   U 8
                   R 5
                   U 3
                   L 9
                   U 1
                   D 7
                   L 7
                   R 5
                   L 8
                   U 8
                   L 9
                   R 10
                   U 1
                   R 5
                   L 5
                   D 7
                   L 8
                   D 5
                   U 4
                   L 4
                   U 6
                   D 4
                   L 8
                   U 8
                   L 10
                   D 1
                   L 2
                   D 3
                   U 8
                   L 7
                   R 7
                   U 6
                   D 4
                   U 8
                   L 2
                   R 6
                   L 7
                   D 11
                   R 4
                   D 9
                   L 10
                   U 3
                   L 9
                   U 10
                   L 11
                   U 11
                   D 2
                   U 4
                   D 5
                   L 11
                   D 4
                   L 6
                   U 2
                   D 8
                   R 4
                   U 4
                   D 5
                   U 8
                   L 3
                   U 2
                   R 7
                   U 10
                   R 5
                   L 3
                   R 11
                   U 2
                   D 8
                   U 3
                   R 10
                   U 10
                   L 3
                   R 7
                   L 8
                   D 5
                   U 9
                   D 9
                   R 3
                   U 4
                   L 6
                   D 9
                   R 10
                   L 2
                   R 8
                   U 11
                   L 2
                   R 1
                   U 11
                   R 2
                   D 3
                   U 9
                   R 3
                   L 2
                   R 1
                   L 6
                   R 10
                   L 2
                   U 6
                   R 4
                   L 9
                   U 11
                   L 1
                   R 11
                   U 8
                   L 4
                   R 11
                   L 6
                   D 5
                   L 11
                   U 3
                   D 5
                   R 5
                   U 2
                   L 3
                   R 4
                   L 9
                   R 7
                   U 11
                   R 7
                   U 7
                   D 10
                   R 11
                   D 10
                   L 3
                   D 5
                   U 2
                   L 1
                   U 2
                   R 2
                   U 8
                   R 1
                   L 10
                   R 10
                   U 5
                   D 4
                   U 4
                   R 4
                   L 8
                   R 6
                   U 9
                   R 5
                   L 3
                   U 9
                   L 3
                   D 4
                   R 10
                   D 11
                   L 12
                   R 1
                   U 11
                   L 10
                   R 11
                   D 10
                   R 10
                   L 4
                   U 11
                   D 2
                   R 8
                   L 6
                   U 7
                   D 7
                   L 12
                   U 1
                   L 3
                   D 8
                   R 6
                   L 7
                   R 11
                   L 2
                   R 6
                   U 2
                   R 2
                   L 2
                   U 5
                   R 12
                   U 12
                   D 12
                   U 1
                   D 6
                   L 5
                   U 3
                   D 3
                   L 4
                   R 10
                   L 5
                   U 2
                   D 8
                   R 4
                   D 5
                   L 7
                   U 2
                   R 10
                   D 12
                   R 9
                   U 11
                   D 10
                   R 4
                   U 2
                   D 1
                   U 10
                   D 8
                   R 2
                   L 9
                   D 12
                   U 12
                   D 2
                   U 8
                   R 5
                   L 8
                   D 5
                   U 9
                   D 8
                   U 7
                   R 3
                   L 10
                   U 11
                   L 5
                   U 12
                   L 2
                   U 9
                   D 7
                   R 12
                   U 9
                   R 2
                   L 3
                   U 10
                   D 9
                   L 7
                   U 5
                   R 3
                   D 3
                   L 11
                   D 1
                   R 5
                   L 1
                   U 5
                   L 6
                   D 8
                   L 2
                   D 5
                   U 8
                   D 9
                   R 8
                   L 7
                   D 6
                   L 6
                   D 1
                   U 5
                   L 4
                   R 6
                   U 9
                   L 3
                   U 3
                   D 7
                   L 1
                   D 4
                   L 9
                   R 9
                   U 6
                   D 8
                   U 12
                   L 5
                   D 4
                   R 7
                   L 2
                   D 4
                   U 7
                   R 7
                   U 2
                   R 13
                   D 5
                   L 1
                   R 5
                   D 6
                   U 2
                   L 1
                   U 5
                   D 2
                   R 9
                   L 8
                   U 9
                   D 9
                   U 12
                   R 10
                   U 9
                   L 13
                   R 5
                   D 10
                   L 9
                   U 4
                   D 12
                   U 12
                   R 13
                   D 12
                   U 7
                   R 12
                   D 8
                   L 8
                   U 2
                   D 10
                   L 2
                   D 5
                   U 3
                   R 11
                   D 4
                   R 4
                   L 1
                   R 1
                   D 9
                   U 6
                   R 10
                   U 12
                   L 10
                   R 13
                   D 7
                   R 12
                   L 5
                   R 10
                   D 4
                   R 11
                   L 7
                   R 7
                   U 7
                   D 7
                   U 11
                   L 3
                   R 9
                   L 12
                   D 11
                   R 5
                   D 5
                   R 7
                   D 7
                   U 3
                   L 11
                   D 11
                   L 10
                   U 7
                   L 13
                   R 6
                   L 10
                   U 10
                   D 10
                   L 4
                   R 5
                   U 5
                   D 2
                   L 6
                   D 8
                   U 1
                   R 12
                   D 11
                   U 3
                   L 9
                   R 10
                   U 8
                   R 10
                   D 2
                   R 3
                   U 9
                   D 7
                   L 6
                   R 9
                   D 2
                   U 11
                   R 3
                   D 1
                   R 4
                   L 11
                   U 13
                   R 12
                   U 12
                   R 8
                   L 13
                   U 7
                   D 10
                   R 11
                   L 2
                   U 9
                   L 3
                   R 5
                   L 4
                   R 11
                   D 5
                   R 1
                   L 11
                   U 10
                   R 4
                   L 1
                   U 2
                   D 8
                   L 7
                   U 1
                   L 4
                   D 1
                   R 1
                   L 11
                   U 8
                   R 11
                   U 4
                   R 10
                   L 6
                   D 7
                   U 9
                   L 14
                   U 1
                   R 10
                   U 12
                   R 1
                   L 6
                   D 9
                   U 10
                   L 10
                   D 5
                   R 14
                   U 3
                   R 13
                   U 3
                   L 13
                   U 8
                   L 10
                   U 7
                   R 12
                   U 11
                   R 6
                   U 6
                   D 6
                   R 2
                   L 7
                   R 8
                   U 8
                   D 3
                   R 8
                   L 12
                   U 11
                   D 9
                   U 6
                   R 8
                   D 8
                   U 9
                   R 12
                   L 11
                   U 10
                   L 14
                   R 9
                   D 8
                   U 14
                   L 9
                   D 11
                   U 2
                   R 2
                   U 4
                   R 7
                   U 11
                   L 8
                   D 12
                   L 11
                   U 13
                   L 1
                   D 8
                   U 8
                   L 10
                   U 12
                   R 11
                   U 3
                   D 12
                   L 1
                   D 8
                   L 4
                   D 3
                   L 2
                   U 8
                   D 9
                   L 1
                   U 9
                   D 15
                   U 5
                   L 9
                   D 2
                   U 4
                   L 2
                   U 15
                   L 8
                   R 2
                   U 1
                   L 3
                   D 10
                   L 15
                   U 2
                   R 14
                   D 1
                   U 13
                   D 4
                   R 8
                   D 6
                   R 5
                   D 13
                   L 5
                   R 6
                   U 14
                   L 15
                   D 15
                   U 12
                   L 1
                   D 3
                   L 6
                   D 2
                   R 4
                   D 10
                   U 12
                   R 13
                   L 3
                   R 15
                   D 13
                   U 15
                   D 14
                   U 8
                   D 10
                   U 5
                   D 11
                   R 15
                   D 7
                   R 1
                   D 2
                   L 5
                   U 11
                   L 14
                   U 9
                   D 13
                   R 12
                   U 10
                   R 11
                   D 9
                   R 6
                   D 7
                   L 7
                   U 14
                   D 12
                   L 6
                   D 15
                   U 11
                   R 1
                   U 3
                   L 11
                   R 3
                   L 9
                   R 9
                   L 11
                   R 12
                   U 6
                   R 13
                   D 13
                   L 9
                   U 3
                   D 6
                   L 4
                   D 3
                   U 15
                   D 13
                   U 9
                   D 1
                   U 13
                   D 12
                   L 4
                   U 6
                   R 11
                   D 2
                   R 7
                   U 9
                   R 11
                   U 3
                   L 7
                   U 4
                   R 2
                   D 14
                   U 3
                   D 14
                   R 13
                   L 4
                   R 1
                   U 12
                   D 10
                   L 8
                   D 2
                   L 15
                   U 1
                   D 4
                   U 16
                   R 15
                   D 1
                   R 8
                   U 14
                   L 12
                   U 2
                   R 1
                   D 16
                   L 10
                   R 11
                   D 10
                   L 15
                   R 7
                   U 10
                   L 3
                   U 11
                   D 1
                   L 5
                   D 3
                   U 8
                   R 3
                   U 5
                   R 2
                   D 11
                   L 2
                   D 7
                   L 2
                   U 3
                   L 12
                   D 13
                   L 12
                   U 7
                   R 11
                   L 4
                   R 11
                   L 8
                   U 16
                   L 1
                   R 11
                   L 4
                   U 15
                   L 16
                   R 15
                   U 6
                   R 4
                   U 3
                   D 16
                   R 9
                   U 8
                   R 5
                   U 6
                   L 2
                   R 2
                   D 10
                   R 7
                   D 13
                   U 13
                   R 14
                   D 3
                   L 15
                   R 3
                   D 11
                   L 4
                   U 12
                   D 1
                   U 8
                   R 8
                   L 4
                   D 6
                   L 15
                   U 7
                   D 15
                   L 11
                   U 14
                   D 8
                   U 15
                   L 12
                   R 6
                   U 13
                   R 5
                   U 2
                   L 1
                   R 13
                   D 10
                   R 7
                   L 9
                   U 14
                   R 1
                   D 13
                   L 11
                   U 9
                   L 13
                   R 5
                   D 14
                   R 16
                   U 5
                   D 9
                   R 2
                   D 5
                   R 8
                   L 8
                   U 16
                   D 12
                   R 3
                   U 3
                   D 5
                   U 12
                   D 14
                   L 9
                   U 12
                   R 6
                   L 9
                   U 3
                   D 16
                   U 15
                   R 6
                   D 11
                   R 10
                   D 3
                   U 16
                   L 11
                   R 2
                   L 2
                   R 9
                   D 12
                   L 8
                   D 8
                   R 13
                   L 5
                   D 17
                   L 7
                   D 10
                   U 13
                   L 11
                   U 17
                   L 13
                   R 2
                   D 6
                   R 14
                   D 14
                   L 15
                   R 8
                   D 4
                   U 7
                   L 6
                   R 6
                   U 7
                   D 12
                   R 9
                   L 8
                   D 15
                   L 14
                   R 1
                   U 8
                   L 13
                   D 16
                   R 2
                   U 2
                   L 2
                   D 13
                   U 8
                   D 6
                   U 10
                   L 9
                   R 2
                   L 7
                   U 5
                   R 6
                   U 12
                   D 3
                   R 1
                   U 4
                   R 17
                   U 11
                   L 3
                   U 13
                   L 12
                   U 6
                   R 5
                   D 12
                   R 4
                   U 4
                   R 3
                   D 11
                   U 7
                   L 10
                   D 12
                   U 12
                   D 9
                   R 4
                   L 2
                   R 9
                   L 13
                   D 16
                   L 14
                   D 5
                   L 8
                   D 6
                   L 13
                   U 1
                   R 7
                   U 5
                   R 2
                   U 11
                   L 10
                   D 14
                   R 11
                   L 5
                   D 16
                   U 9
                   D 3
                   U 11
                   D 1
                   U 5
                   D 3
                   U 8
                   L 1
                   D 1
                   U 5
                   L 17
                   D 9
                   L 14
                   R 8
                   D 15
                   R 10
                   U 4
                   R 1
                   U 3
                   R 5
                   L 13
                   D 6
                   L 15
                   U 10
                   L 5
                   R 14
                   L 1
                   R 6
                   D 10
                   L 13
                   D 3
                   L 1
                   U 10
                   D 6
                   R 16
                   D 6
                   R 4
                   D 9
                   U 9
                   D 4
                   R 1
                   D 10
                   R 7
                   D 14
                   R 10
                   D 14
                   U 14
                   D 15
                   R 11
                   L 16
                   D 18
                   R 6
                   U 8
                   D 18
                   R 18
                   D 14
                   U 9
                   R 18
                   U 14
                   L 18
                   U 1
                   R 14
                   D 1
                   U 6
                   R 3
                   L 13
                   D 4
                   L 9
                   D 2
                   U 5
                   D 6
                   U 9
                   L 13
                   U 12
                   R 11
                   D 17
                   U 17
                   L 8
                   U 15
                   R 16
                   L 9
                   D 2
                   R 16
                   D 2
                   L 9
                   D 9
                   R 15
                   D 10
                   L 12
                   R 14
                   L 4
                   R 17
                   D 15
                   U 16
                   R 7
                   D 4
                   U 4
                   L 7
                   D 16
                   R 11
                   D 2
                   U 2
                   L 7
                   U 15
                   L 5
                   U 14
                   L 7
                   U 15
                   D 9
                   L 14
                   D 13
                   U 11
                   R 10
                   U 15
                   L 5
                   U 16
                   D 13
                   U 15
                   L 18
                   R 1
                   D 17
                   U 18
                   R 19
                   L 4
                   R 15
                   U 12
                   D 19
                   R 5
                   D 18
                   L 14
                   U 5
                   L 4
                   R 6
                   U 15
                   L 7
                   R 11
                   L 15
                   U 12
                   D 3
                   R 14
                   U 1
                   L 4
                   R 3
                   U 15
                   L 15
                   R 6
                   L 3
                   U 2
                   D 6
                   L 6
                   D 16
                   L 19
                   U 9
                   L 2
                   R 13
                   U 8
                   R 17
                   D 17
                   L 4
                   R 2
                   L 7
                   R 11
                   D 5
                   L 14
                   D 7
                   R 13
                   D 2
                   L 18
                   U 11
                   R 2
                   D 18
                   U 2
                   D 6
                   L 4
                   U 2
                   L 15
                   R 4
                   D 8
                   R 1
                   U 16
                   L 4
                   R 5
                   U 16
                   D 14
                   U 2
                   D 19
                   L 6
                   D 14
                   U 17
                   L 3
                   R 11
                   L 2
                   R 11
                   U 11
                   D 4
                   U 13
                   L 6
                   U 14
                   D 17
                   U 15
                   D 7
                   R 8
                   U 3
                   R 15
                   D 17
                   U 16
                   R 3
                   D 17
                   L 9
                   U 15
                   R 15
                   L 11
                   R 18
                   D 16
                   R 17
                   D 3
                   L 17
                   D 4
                   L 10
                   U 2
                   R 2
                   D 9
                   L 17
                   R 19
                    """;
}
